[package]
name = "weather_station_backend"
version = "0.3.1"
authors = ["Tim Hütz <tim@huetz.biz>"]
edition = "2018"

[[bin]]
name = "weather_station_backend"
path = "src/bin/main.rs"

[dependencies]
chrono = "0.4"
clap = {version = "2.33", features = ["yaml"]}
fern = "0.6"
futures = "0.1"
hyper = "0.12"
log = "0.4"
rocket = "0.4"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
serde_yaml = "0.8"
