[package]
name = "weather_station_backend"
version = "0.0.1"
authors = ["Tim Hütz <tim@huetz.biz>"]
edition = "2018"

[[bin]]
name = "weather_station_backend"
path = "src/bin/main.rs"

[dependencies]
log = "0.4.6"
simplelog = "0.5.3"
serde = { version = "1.0.91", features = ["derive"] }
serde_json = "1.0.39"
dotenv = "0.14.1"
diesel = { version = "1.4.2", features = ["mysql"] }