[package]
name = "weather_station_backend"
version = "0.0.1"
authors = ["Tim Hütz <tim@huetz.biz>"]
edition = "2018"

[[bin]]
name = "weather_station_backend"
path = "src/bin/main.rs"

[dependencies]
log = "0.4.6"
simplelog = "0.5.3"
rocket = "0.4.1"
rocket_codegen = "0.4.1"
serde = "1.0.91"
serde_json = "1.0.39"
serde_derive = "1.0.91"

[dependencies.rocket_contrib]
version = "*"
default-features = false
features = ["json"]
