version: "3"
services:
  influxdb:
    container_name: influxdb
    image: influxdb:latest
    volumes:
      - ./devenv/influxdb:/var/lib/influxdb
    ports:
      - "8086:8086/tcp"
    healthcheck:
      test: ['CMD', 'curl', '-sfl', '-I', 'http://influxdb:8086/ping']
      interval: 1m30s
      timeout: 10s