[package]
name = "weather_station_backend"
version = "0.1.1"
authors = ["Tim Hütz <tim@huetz.biz>"]
edition = "2018"

[[bin]]
name = "weather_station_backend"
path = "src/bin/main.rs"

[dependencies]
log = "0.4.6"
hyper = "0.12.29"
fern = "0.5.8"
chrono = "0.4.6"
serde = { version = "1.0.91", features = ["derive"] }
serde_json = "1.0.39"
dotenv = "0.14.1"
diesel = { version = "1.4.2", features = ["mysql", "chrono"] }
futures = "0.1.27"

[dev-dependencies]
mockers = "0.20.0"
mockers_derive = "0.20.0"
