[package]
name = "weather_station_backend"
version = "0.1.1"
authors = ["Tim Hütz <tim@huetz.biz>"]
edition = "2018"

[[bin]]
name = "weather_station_backend"
path = "src/bin/main.rs"

[dependencies]
log = "*"
hyper = "*"
fern = "*"
chrono = "*"
serde = { version = "*", features = ["derive"] }
serde_json = "*"
dotenv = "*"
diesel = { version = "*", features = ["mysql", "chrono"] }
futures = "*"

[dev-dependencies]
mockers = "*"
mockers_derive = "*"
