[package]
name = "weather_station_backend"
version = "0.1.1"
authors = ["Tim Hütz <tim@huetz.biz>"]
edition = "2018"

[[bin]]
name = "weather_station_backend"
path = "src/bin/main.rs"

[dependencies]
afluencia = { path = "../afluencia" }
chrono = "0.4.6"
diesel = { version = "1.4.2", features = ["mysql", "chrono"] }
dotenv = "0.14.1"
fern = "0.5.8"
futures = "0.1.27"
hyper = "0.12.29"
lazy_static = "1.3.0"
log = "0.4.6"
serde = { version = "1.0.91", features = ["derive"] }
serde_json = "1.0.39"
