[package]
name = "afluencia"
version = "0.0.1"
authors = ["Tim Hütz <tim@huetz.biz>"]
edition = "2018"

[lib]
name = "afluencia"
path = "src/lib.rs"

[dependencies]
hyper = "0.12"
log = "0.4"
futures = "0.1"